  version: '3.8'
  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 2224:5000
      depends_on:
        - db
    db:
      image: lscr.io/linuxserver/sqlitebrowser:latest
      volumes:
        - ./data:/data

